version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 10
    target-branch: "dependabot-dev"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "ViktorPopp"
    assignees:
      - "ViktorPopp"
