[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true                           # Or remove this from Cargo.toml: `panic = "abort"`

[build]
target = "x86_64-infinity_os.json"
rustflags = ["-C", "force-frame-pointers=yes"]

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
