[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
panic-abort-tests = true # Or remove this from Cargo.toml: `panic = "abort"`

[build]
target = "x86_64-infinity_os.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"