name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  release:
    name: Build and Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          override: true

      - name: Install required Rust components
        run: |
          rustup component add rust-src --toolchain nightly
          rustup component add llvm-tools-preview --toolchain nightly

      - name: Install bootimage
        run: cargo install bootimage

      - name: Build Infinity OS
        if: ${{ env.commits_since != '0' }}
        run: cargo bootimage
